- name: Instalando dependencias
  apt:
    name: "{{ item }}"
    state: present
  with_items:
  - "apt-transport-https"
  - "ca-certificates"
  - "curl"
  - "software-properties-common"
  when: ansible_distribution == "Ubuntu"
- name: Adiconando a chave do repositorio
  apt_key:
    url: "https://download.docker.com/linux/ubuntu/gpg"
    state: present
- name: Adicionando repositorio
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present
- name: Instalando Docker CE
  apt:
    name: docker-ce
    state: present
    update_cache: yes
- name: Iniciando o docker
  service:
    name: docker
    state: started
    enabled: true
